# Generated by Django 3.2.9 on 2021-11-16 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='goals',
        ),
        migrations.AddField(
            model_name='goals',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.items'),
        ),
    ]
